# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tutorial Java
email: burhan@jombelajarjava.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/java" # the subpath of your site, e.g. /blog
url: "https://www.jombelajarjava.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  JomBelajarJava
google_analytics: UA-64328787-1
google_adsense: ca-pub-8041854815282465

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  - pengenalan
  - asas
  - oop
  - essentials
  - datastructure
  - database
  - quality

collections:
  pengenalan:
    output: true
  asas:
    output: true
    permalink: /:collection/:name
  oop:
    output: true
    permalink: /:collection/:name
  essentials:
    output: true
    permalink: /:collection/:name
  datastructure:
    output: true
    permalink: /:collection/:name
  database:
    output: true
    permalink: /:collection/:name
  quality:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "pengenalan"
    values:
      layout: "tutorial"
  - scope:
      path: ""
      type: "asas"
    values:
      layout: "tutorial"
  - scope:
      path: ""
      type: "oop"
    values:
      layout: "tutorial"
  - scope:
      path: ""
      type: "essentials"
    values:
      layout: "tutorial"
  - scope:
      path: ""
      type: "datastructure"
    values:
      layout: "tutorial"
  - scope:
      path: ""
      type: "database"
    values:
      layout: "tutorial"
  - scope:
      path: ""
      type: "quality"
    values:
      layout: "tutorial"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
